environment:
  matrix:
    - BUILDER: msvc
    - BUILDER: clang
    - BUILDER: mingw

install:
  #
  # Set PATH to the needed POSIX tools
  #
  - cmd: set PATH=c:\msys64\usr\bin;%PATH%

  #
  # But this shadows the MSVC link program. Just delete it.
  #
  - cmd: del c:\msys64\usr\bin\link.exe

  - cmd: if %BUILDER%. == msvc.  call "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
  - cmd: if %BUILDER%. == clang. call "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
  - cmd: set PATH=c:\Program Files (x86)\LLVM\bin;%PATH%

  #
  # Download LLVM-MinGW from Github first.
  #
  # TODO: check if '%LLVM_MINGW%\bin\gcc.exe' exist first.
  # I.e. preserved by the below 'cache:' statement
  #
  - if %BUILDER%. == mingw. (curl -LO https://github.com/mstorsjo/llvm-mingw/releases/download/20251021/llvm-mingw-20251021-msvcrt-x86_64.zip & 7z x -y -bd llvm-mingw-20251021-msvcrt-x86_64.zip)

build_script:
  - set MAKE=make -f Makefile.Windows CPU=x64
  - set OPT=USE_LIBUSB=0 USE_LIBUSRP=0 USE_WSOCK_TRACE=0 USE_LIBXML2=0 USE_LIBGD=0 USE_LIBREADLINE=0 USE_PY_BINDING=0 USE_LUA_BINDING=0 USE_GNURADIO=0
  - set LLVM_MINGW=%APPVEYOR_BUILD_FOLDER%\llvm-mingw-20251021-msvcrt-x86_64

  - if %BUILDER%. == msvc.  %MAKE% %OPT% CC=cl
  - if %BUILDER%. == clang. %MAKE% %OPT% CC=clang-cl
  - if %BUILDER%. == mingw. %MAKE% %OPT% CC=gcc

  #
  # Not yet possible; need to add Lua as a submodule etc.
  #
  # - if %BUILDER%. == msvc.  %MAKE% CC=cl       py_module lua_module
  # - if %BUILDER%. == clang. %MAKE% CC=clang-cl py_module lua_module

test_script:
  #
  # List all supported Radios, Rotators and Amplifiers
  #
  - cmd: set PATH=%PATH%;%LLVM_MINGW%\bin

  - echo ---------------------------------------------------------------------------------------------------
  - bin\rigctl.exe --list
  - echo ---------------------------------------------------------------------------------------------------
  - bin\rotctl.exe --list
  - echo ---------------------------------------------------------------------------------------------------
  - bin\ampctl.exe --list

#
# Try to preserve previously downloaded CI package
#
cache:
  - '%LLVM_MINGW%'
