environment:
  matrix:
    - BUILDER: mingw
      CPU:     x86
    - BUILDER: mingw
      CPU:     x64
    - BUILDER: msvc
      CPU:     x86
    - BUILDER: msvc
      CPU:     x64

install:
  #
  # Set PATH to the needed POSIX tools
  #
  - cmd: set PATH=c:\msys64\usr\bin;%PATH%

  #
  # But this shadows the MSVC link program. Just delete it.
  #
  - cmd: del c:\msys64\usr\bin\link.exe

  - cmd: if %BUILDER%. == msvc.            call "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %CPU%
  - cmd: if %BUILDER%-%CPU%. == mingw-x86. set PATH=c:\msys64\MinGW32\bin;%PATH%
  - cmd: if %BUILDER%-%CPU%. == mingw-x64. set PATH=c:\msys64\MinGW64\bin;%PATH%

build_script:
  - set MAKE=make -f Makefile.Windows USE_LIBUSB=0 USE_USRP=0 USE_WSOCK_TRACE=0 USE_LIBXML2=0 USE_LIBGD=0 USE_LIBREADLINE=0 USE_LUAJIT=0 USE_GNURADIO=0
  - if %BUILDER%. == msvc.  %MAKE% CPU=%CPU% CC=cl
  - if %BUILDER%. == mingw. %MAKE% CPU=%CPU% CC=gcc

