environment:
  matrix:
    - BUILDER: msvc
    - BUILDER: clang
    - BUILDER: mingw

install:
  #
  # Set PATH to the needed POSIX tools
  #
  - cmd: set PATH=c:\msys64\usr\bin;%PATH%

  #
  # But this shadows the MSVC link program. Just delete it.
  #
  - cmd: del c:\msys64\usr\bin\link.exe

  - cmd: if %BUILDER%. == msvc.  call "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
  - cmd: if %BUILDER%. == clang. call "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
  - cmd: if %BUILDER%. == mingw. set PATH=c:\msys64\MinGW64\bin;%PATH%
  - cmd: set PATH=c:\Program Files (x86)\LLVM\bin;%PATH%

build_script:
  - set OPTIONS=USE_LIBUSB=0 USE_LIBUSRP=0 USE_WSOCK_TRACE=0 USE_LIBXML2=0 USE_LIBGD=0 USE_LIBREADLINE=0 USE_LUAJIT=0 USE_GNURADIO=0 USE_PTHREAD=0
  - set MAKE=make -f Makefile.Windows CPU=x64 %OPTIONS%
  - if %BUILDER%. == msvc.  %MAKE% CC=cl
  - if %BUILDER%. == mingw. %MAKE% CC=gcc
  - if %BUILDER%. == clang. %MAKE% CC=clang-cl

  #
  # Not yet possible; need to add Lua as a submodule etc.
  #
  # - if %BUILDER%. == msvc.  %MAKE% CC=cl       py_module lua_module
  # - if %BUILDER%. == mingw. %MAKE% CC=gcc      py_module lua_module
  # - if %BUILDER%. == clang. %MAKE% CC=clang-cl py_module lua_module

test_script:
  #
  # List all supported Radios, Rotators and Amplifiers
  #
  - echo ---------------------------------------------------------------------------------------------------
  - rigctl.exe --list
  - echo ---------------------------------------------------------------------------------------------------
  - rotctl.exe --list
  - echo ---------------------------------------------------------------------------------------------------
  - ampctl.exe --list

